export const colors = {
  backgroundPrimary: '#FFFFFF',
  backgroundSurfaceZ1: '#FFFFFF',
  backgroundSurfaceZ2: '#F7F7F7',
  backgroundSecondary: '#F7F7F7',
  backgroundTertiary: '#EFF0F1',
  backgroundAccent: '#04B488',
  backgroundNegative: '#ED5533',
  backgroundPositive: '#04B488',
  backgroundWarning: '#E7A71E',
  backgroundAccentSubtle: '#E9FAF3',
  backgroundNegativeSubtle: '#FFF1ED',
  backgroundPositiveSubtle: '#E9FAF3',
  backgroundWarningSubtle: '#FFF7DE',
  backgroundDisabled: '#F7F7F7',
  borderPrimary: '#E7E8E9',
  borderAccent: '#04B488',
  borderNegative: '#ED5533',
  borderDisabled: '#EFF0F1',
  borderNeutral: '#353839',
  contentPrimary: '#353839',
  contentSecondary: '#7F8283',
  contentTertiary: '#898C8E',
  contentDisabled: '#BABBBC',
  contentAccent: '#04B488',
  contentPositive: '#04B488',
  contentNegative: '#ED5533',
  contentWarning: '#E7A71E',
  contentOnColour: '#FFFFFF',
  contentOnAccentSubtle: '#00825C',
  contentOnPositiveSubtle: '#00825C',
  contentOnNegativeSubtle: '#D23A15',
  contentOnWarningSubtle: '#A16B00',
};

export const fonts = {
  sohne: 'Sohne-Kraftig',
  growwSansRegular: 'GrowwSans-Regular',
  growwSansMedium: 'GrowwSans-Medium',
};

export const textStyles = {
  bodySmall: { fontFamily: fonts.growwSansRegular, fontSize: 12, lineHeight: 18 },
  bodySmallHeavy: { fontFamily: fonts.growwSansMedium, fontSize: 12, lineHeight: 18 },
  bodyBase: { fontFamily: fonts.growwSansRegular, fontSize: 14, lineHeight: 20 },
  bodyBaseHeavy: { fontFamily: fonts.growwSansMedium, fontSize: 14, lineHeight: 20 },
  bodyLarge: { fontFamily: fonts.growwSansRegular, fontSize: 16, lineHeight: 24 },
  bodyLargeHeavy: { fontFamily: fonts.growwSansMedium, fontSize: 16, lineHeight: 24 },
  headingEyebrow: { fontFamily: fonts.sohne, fontSize: 10, lineHeight: 12, letterSpacing: 2 },
  headingXSmall: { fontFamily: fonts.sohne, fontSize: 14, lineHeight: 20 },
  headingSmall: { fontFamily: fonts.sohne, fontSize: 16, lineHeight: 24 },
  headingBase: { fontFamily: fonts.sohne, fontSize: 18, lineHeight: 28 },
  headingLarge: { fontFamily: fonts.sohne, fontSize: 20, lineHeight: 32 },
  displaySmall: { fontFamily: fonts.sohne, fontSize: 24, lineHeight: 32 },
  displayBase: { fontFamily: fonts.sohne, fontSize: 28, lineHeight: 36 },
};
